version: '2'

services:
  # mailman-dev:
  #   image: ghcr.io/maxking/mailman-ci-runner:latest
  #   container_name: mailman-dev
  #   hostname: mailman-dev
  #   links:
  #   - database:database
  #   depends_on:
  #   - database
  #   command:
  #   - bash
  #   - -c
  #   - 'sleep infinity'

  database:
    environment:
      MYSQL_DATABASE: mailmandb
      MYSQL_USER: mailman
      MYSQL_PASSWORD: mailmanpass
      MYSQL_ROOT_PASSWORD: my-secret-pw
    image: mysql:5.6
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci